version: "3"
services:
  ctfovid:
    image: sebp/lighttpd
    volumes:
      - ./root:/var/www/localhost/htdocs
    environment:
      - VIRTUAL_HOST=ctfovid.ctf.sicamp.ru
    tty: true
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true