version: '3.0'

services:
  marks:
    build:
      context: .
      dockerfile: docker_config/backend/Dockerfile
    restart: on-failure

  bot:
    build: 
      context: .
      dockerfile: docker_config/bot/Dockerfile
    restart: on-failure

  redis:
    image: redis:5.0.5-alpine
    restart: on-failure
  
  nginx:
    image: nginx:1.17
    volumes:
      - ./marks/static:/static
      - ./docker_config/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - marks
    environment:
      - VIRTUAL_HOST=marks.ctf.sicamp.ru
    restart: unless-stopped
    networks:
      - proxy
      - default
networks:
  proxy:
    external: true