version: '3.3'
services:
  students-quite-literate:
    build: ./
    environment:
      - VIRTUAL_HOST=students-quite-literate.ctf.sicamp.ru
    networks:
      - proxy

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: susekere
      MYSQL_DATABASE: app

networks:
  proxy:
    external: true