version: '3.3'
services:
  students-quite-literate:
    build: ./
    ports:
      - 127.0.0.1:33011:80

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: susekere
      MYSQL_DATABASE: app
